// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

String greet({required String name}) =>
    RustLib.instance.api.crateApiSimpleGreet(name: name);

Future<int> add({required int a, required int b}) =>
    RustLib.instance.api.crateApiSimpleAdd(a: a, b: b);

void initAndWatchConfig() =>
    RustLib.instance.api.crateApiSimpleInitAndWatchConfig();

String getConfig({PathBuf? path, String? id}) =>
    RustLib.instance.api.crateApiSimpleGetConfig(path: path, id: id);

Future<String> getTables({required String name}) =>
    RustLib.instance.api.crateApiSimpleGetTables(name: name);

String configToJson({required Config config}) =>
    RustLib.instance.api.crateApiSimpleConfigToJson(config: config);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Config>>
abstract class Config implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<PathBuf>>
abstract class PathBuf implements RustOpaqueInterface {}
